#!/bin/sh
# Generate template content for a C/C++ header file.
# usage : $0 <filename>

[ -z "$1" ] && exit 1

head_def=`echo _${1}__ | tr "a-z.-" "A-Z__"`

cat << EOF
/*
 * Copyright (C) 2018 by [Group Name] Limited. All rights reserved.
 * author-name <author-mail@address.com>
 */

#ifndef ${head_def}
#define ${head_def}


#endif  // ${head_def}
EOF
